### ISSUE TITLE
ValueError('need at least one array to stack')

### ISSUE THREAD

**Issue by yijingshihenxiule** [SheldonTsui/PseudoBinaural_CVPR2021#1]
When I use APNet_train_crop.sh or APNet_train.sh to run the code, there is an error:

>Traceback (most recent call last):
  File "train.py", line 210, in <module>
    for i, data in enumerate(data_loader):
  File "/home/yzx/anaconda3/envs/pytorch/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 517, in __next__
    data = self._next_data()
  File "/home/yzx/anaconda3/envs/pytorch/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1199, in _next_data
    return self._process_data(data)
  File "/home/yzx/anaconda3/envs/pytorch/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1225, in _process_data
    data.reraise()
  File "/home/yzx/anaconda3/envs/pytorch/lib/python3.8/site-packages/torch/_utils.py", line 429, in reraise
    raise self.exc_type(msg)
ValueError: Caught ValueError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/yzx/anaconda3/envs/pytorch/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 202, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/yzx/anaconda3/envs/pytorch/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/yzx/anaconda3/envs/pytorch/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/yzx/lunwen/PseudoBinaural_CVPR2021-master/data/Augment_dataset.py", line 66, in __getitem__
    data_ret, data_ret_sep = self._get_pseudo_item(index)
  File "/home/yzx/lunwen/PseudoBinaural_CVPR2021-master/data/Pseudo_dataset.py", line 263, in _get_pseudo_item
    stereo = self.construct_stereo_ambi(pst_sources)
  File "/home/yzx/lunwen/PseudoBinaural_CVPR2021-master/data/Pseudo_dataset.py", line 120, in construct_stereo_ambi
    signals = np.stack([src.signal for src in pst_sources], axis=1) # signals shape: [Len, n_signals]
  File "<__array_function__ internals>", line 5, in stack
  File "/home/yzx/anaconda3/envs/pytorch/lib/python3.8/site-packages/numpy/core/shape_base.py", line 423, in stack
    raise ValueError('need at least one array to stack')

    Before the running ,I remade the hdf5 file and train_FAIR_data.txt,  the sequences of them are all  according to the sequence of the content of ./new_splits/split1，for example，the first line of train_FAIR_data.txt is “/home/yzx/lunwen/datasets/FAIR-PLAY/binaural_audios/000383.wav,/home/yzx/lunwen/datasets/FAIR-PLAY/frames/000383”. The former means the path of each binaural_audio，the latter is the path of the frames corresponding to the binaural_audio. For each video, I take the method of  
Extracting 10 frames per second as your code. Because I found that in the function “_get_pseudo_item” in Pseudo_dataset.py，They are splited to audio_file and img_folder respectively. But I don't know why there is always the problem. I am eager for your help.

**Comment by SheldonTsui** [comment]
@yijingshihenxiule I have removed the annoying h5 split and replaced them with convenient 'txt' files. Now, you just need to modify the item in 'new_splits' into the absolute path as illustrated in the updated README.

**Comment by yijingshihenxiule** [comment]
> @yijingshihenxiule I have removed the annoying h5 split and replaced them with convenient 'txt' files. Now, you just need to modify the item in 'new_splits' into the absolute path as illustrated in the updated README.

Thank you for your reply. I have followed your revise, and made some some another revises in stereo_dataset.py, or it will report FileNotFound error. But there is still my previous error "need at least one array to stack". I don't know why.

**Comment by SheldonTsui** [comment]
@yijingshihenxiule I'm sorry. The items in 'data/mono_sources' should also be replaced with the absolute path. Just refer to the updated README.

**Comment by yijingshihenxiule** [comment]
> @yijingshihenxiule I'm sorry. The items in 'data/mono_sources' should also be replaced with the absolute path. Just refer to the updated README.

Yes, I have followed README. But the error still exists.
This is the my revised "./new_splits/split1/train.txt .
[train.txt](https://github.com/SheldonTsui/PseudoBinaural_CVPR2021/files/6505601/train.txt)

,and this is my "./data/mono_sources/train_FAIR_data.txt
[train_FAIR_data.txt](https://github.com/SheldonTsui/PseudoBinaural_CVPR2021/files/6505603/train_FAIR_data.txt)
I think my revise is right. But the error "ValueError('need at least one array to stack')" is still there. I believe my absolute paths are all right.

**Comment by SheldonTsui** [comment]
Hello, @yijingshihenxiule. Please mind that the latter item in 'data/mono_sources/train_FAIR_data.txt' is NOT the frame, but the cropped patches. For every image in the frame folder, you should crop that object patch out and store them in them 'new_patches' folder. I used the Faster-RCNN model adopted from this repo [https://github.com/rhgao/co-separation](url). Good luck!

**Comment by yijingshihenxiule** [comment]
> Hello, @yijingshihenxiule. Please mind that the latter item in 'data/mono_sources/train_FAIR_data.txt' is NOT the frame, but the cropped patches. For every image in the frame folder, you should crop that object patch out and store them in them 'new_patches' folder. I used the Faster-RCNN model adopted from this repo [https://github.com/rhgao/co-separation](url). Good luck!

Thank you for your reply. I will try the step that you said above. But actually I try all the .sh files in the './scripts', they all have the same error. I suppose they are generated when loading audios in Pseudo_dataset.py. I wil check for more.
