### ISSUE TITLE
How to calculate virtual array in the code

### ISSUE THREAD

**Issue by 310mo** [SheldonTsui/PseudoBinaural_CVPR2021#2]
Thank you for your great research. I have read your paper and I am reading the code. I have a question on how to calculate the “virtual speakers” when making pseudo binaural sound.
In your paper, you calculate the “virtual array” in equation (7).
<img width="390" alt="スクリーンショット 2021-05-28 4 04 26" src="https://user-images.githubusercontent.com/26376945/119882820-cdca7180-bf69-11eb-914a-2f7f647be885.png">
I think the same calculation is performed by `costruct_stereo_ambi` function in `data/Pseudo_dataset.py` in your code.
I understand that variables in this function correspond to equation (7) as follows.
<img src="https://user-images.githubusercontent.com/26376945/119882350-48df5800-bf69-11eb-9e30-ef51edb76a28.png" width=35%>
Here, in `data/Pseudo_dataset.py` line 123, we have
`array_speakers_sound = np.dot(ambisonic, self.sph_mat.T)`
but I cannot understand how <img width="149" alt="スクリーンショット 2021-05-28 4 07 18" src="https://user-images.githubusercontent.com/26376945/119883178-33b6f900-bf6a-11eb-831a-712cb3347434.png" width=20%> Is taken into account.
I would like to know how you reflect the calculation of equation (7) in your code.
Regards.

**Comment by SheldonTsui** [comment]
Hi, @310mo  In the below line (line 124), we had tried to use the pseudo inverse to represent the item (D^T D)^{-1} D^T. In the implementation, we found that the performance was not affected if we replaced the pseudo inverse with a simpler transpose item. Therefore, we commented line 124 out and just used line 123 to accelerate the training.

**Comment by 310mo** [comment]
Thank you very much!
I see the point.
