### ISSUE TITLE
 'new_patches' folder

### ISSUE THREAD

**Issue by zhexian949** [SheldonTsui/PseudoBinaural_CVPR2021#3]
Hello, I find that you mentioned  'new_patches' folder, but I don't find that in this repo. Shall I do it by myself? Can you provide it for me? Thank you!

**Comment by SheldonTsui** [comment]
Hi, @zhexian949 You have to prepare it by yourself. For the details, please refer to my response in #1.

**Comment by zhexian949** [comment]
Thank you. I will have a try.

**Comment by zhexian949** [comment]
Hello, @SheldonTsui ,could you share the new_patches folder results of FAIR-PLAY data set? I try to use the repo in the Readme, but failed. Maybe I did not fully understand that. Thank you!

**Comment by SheldonTsui** [comment]
Hi, @zhexian949 I have put the new_patches folder in the google driver. Please refer to this link: https://drive.google.com/file/d/1t0S9Lq82OLd8pQkppRkrET4Lx2PTEt-K/view?usp=sharing
