### ISSUE TITLE
about the result

### ISSUE THREAD

**Issue by zhexian949** [SheldonTsui/PseudoBinaural_CVPR2021#5]
Hi. I test the model that you hava listed in the Readme. But the result is like this 

- ./eval_demo/sepstereo_Augment/Augment_AudioNet_sepstereo_crop_1_best
STFT L2 Distance: 1.2610043297237892
Average Envelope Distance: 0.16047628236511588
MSE Distance: 0.008410530806834097
STFT MSE Distance: 2.5220085946633852
Mag diff Distance: 18.28601552585867
Average Envelope diff Distance: 1.5206958858724584
Snr: 5.251474191632674
L1 Distance: 0.4755515200011233

This result is not as good as that in the paer.

And I trained a model by myself with the ./scripts/sepstereo_Augment/audionet_train_crop.sh, but the result is worse, which is shown below
- ./eval_demo/sepstereo_Augment/Augment_AudioNet_sepstereo_crop_1_best
STFT L2 Distance: 1.3221603853498551
Average Envelope Distance: 0.16612554087451462
MSE Distance: 0.008804865650220072
STFT MSE Distance: 2.6443207939678337
Mag diff Distance: 17.008346246525566
Average Envelope diff Distance: 1.4829492619968354
Snr: 5.008793861205568
L1 Distance: 0.4820237934270645

Could you help me how to improve the result? I am sincerely eager for your help.

**Comment by SheldonTsui** [comment]
Hi, @zhexian949 The result in the paper is the average result on five new splits as listed in this repo, not only the result on split1. For the model trained by yourself, I don't know whether you follow my setting correctly. Note that, if you do the training in the sepstereo mode, the 'train.py' script should be slightly modified as mentioned in #4.

**Comment by zhexian949** [comment]
Hi, @SheldonTsui . I followed the steps and settings in the Readme. The answer in #4 may be helpful for me. I will hava a try.

**Comment by zhexian949** [comment]
Hi, @SheldonTsui .I have another question. I would like to know whether the config 'dataset_mode' of 'Augment_sepstereo' corresponds to Augment-PseudoBinaural in the paper.

**Comment by SheldonTsui** [comment]
Hi, @zhexian949. Yes, 'Augment_sepstereo' is Augment-PseudoBinaural in the paper.

**Comment by krantiparida** [comment]
Hi, @SheldonTsui. The trained models provided in the link [here](https://drive.google.com/drive/folders/1ZbGzTjHjxSioxpXlQeTKtIDFE_gg2Plk) for APNet case doesn't have the weights for the fusion model required for reproducing the results. can you please share that as well, please? Also if you can provide the results for each of the five splits for FAIR-PLAY it would be quite helpful.

**Comment by SheldonTsui** [comment]
@krantiparida I have uploaded the checkpoints from AudioNet and APNet to the original link.
