### ISSUE TITLE
Will there be big difference using different HRIR?

### ISSUE THREAD

**Issue by sukun1045** [SheldonTsui/PseudoBinaural_CVPR2021#7]
Hi, I have a question regarding the HRIR used in the experiment. Is the HRIR data from the CIPIC HRTF Database? It seems like you are using only the subject 3 data. I am wondering whether there will be a big difference if you are using HRIR for other subjects. Thank you.

**Comment by SheldonTsui** [comment]
Yes, it's from the CIPIC HRTF database. I just use subject 3 data as default and am not sure there's a big difference.

**Comment by sukun1045** [comment]
Thanks for your reply. I have another question regarding the virtual speakers. In the experiment, the number of speakers in the virtual array is 8, right? In the supplementary material you mention this is following the common practice, could you tell me the reference to this common setup? Also, why are they placed around the frontal part of the head in a uniform way? Would it be better if placed at different elevations and azimuth angles? thank you.

**Comment by SheldonTsui** [comment]
We here leverage the virtual speaker array to compensate for the room reverberation and take the code of previous work "Self-Supervised Generation of Spatial Audio for 360° Video" as the reference. For the details, you can refer to https://github.com/pedro-morgado/spatialaudiogen
